### ISSUE TITLE
Subsection III is missing in chapter 7

### ISSUE THREAD

**Issue by solt87** [standardebooks/arthur-quiller-couch_on-the-art-of-reading#4]
In chapter seven the subsection headings go from I to X, but III is
missing. It's the same in the linked PG source. I can't tell if the
actual subsection is missing as well, or only its heading. I looked at
the linked Google Books page, but I couldn't find a way to actually check
that version.

Is there any reasonably way to find out what the exact error is and how
the text is supposed to look? (E.g. maybe nothing is missing, and the
headings just got shifted after "II".)

**Comment by acabal** [comment]
In the scans it looks like section 3 was the couple of paragraphs before section 4. I've fixed this, thanks!
